<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1661083938417' stop='1661083998510'>
    <name>Setmore Add Staff</name>
    <title>Setmore Add Staff</title>
    <test-cases>
        <test-case start='1661083938418' status='broken' stop='1661083998508'>
            <name>Adding staff in setmore</name>
            <title>Adding staff in setmore</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-6'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome-104.0.5112.82'/>
            </parameters>
            <steps>
                <step start='1661083938505' status='broken' stop='1661083998507'>
                    <name>POST /session/:sessionId/url</name>
                    <title>POST /session/:sessionId/url</title>
                    <attachments>
                        <attachment title='Request' source='03801321-9b60-4277-8dab-341fb8295ddf-attachment.json' type='application/json' size='48'/>
                    </attachments>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Timeout of 60000ms exceeded. The execution in the test "Setmore Add Staff Adding staff in setmore" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (C:\Users\LENOVO\Desktop\Wdio_Scripts\test\specs\Setmore_staff.js)</message>
                <stack-trace>Error: Timeout of 60000ms exceeded. The execution in the test "Setmore Add Staff Adding staff in setmore" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (C:\Users\LENOVO\Desktop\Wdio_Scripts\test\specs\Setmore_staff.js)
                    at createTimeoutError (C:\Users\LENOVO\Desktop\Wdio_Scripts\node_modules\mocha\lib\errors.js:498:15)
                    at Test.Runnable._timeoutError (C:\Users\LENOVO\Desktop\Wdio_Scripts\node_modules\mocha\lib\runnable.js:431:10)
                    at Timeout.&lt;anonymous> (C:\Users\LENOVO\Desktop\Wdio_Scripts\node_modules\mocha\lib\runnable.js:246:24)
                    at listOnTimeout (node:internal/timers:559:17)
                    at processTimers (node:internal/timers:502:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>