<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1664273813140' stop='1664273873155'>
    <name>Setmore SignUp feature</name>
    <title>Setmore SignUp feature</title>
    <test-cases>
        <test-case start='1664273813141' status='broken' stop='1664273873153'>
            <name>User should sign up with valid credentials</name>
            <title>User should sign up with valid credentials</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-5'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome-105.0.5195.127'/>
            </parameters>
            <steps>
                <step start='1664273813146' status='broken' stop='1664273873153'>
                    <name>POST /session/:sessionId/url</name>
                    <title>POST /session/:sessionId/url</title>
                    <attachments>
                        <attachment title='Request' source='74d6573e-7515-457f-aa9b-cd44addfcefd-attachment.json' type='application/json' size='48'/>
                    </attachments>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Timeout of 60000ms exceeded. The execution in the test "Setmore SignUp feature User should sign up with valid credentials" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (C:\Users\LENOVO\Desktop\Wdio_Scripts\test\specs\Setmore_signup.js)</message>
                <stack-trace>Error: Timeout of 60000ms exceeded. The execution in the test "Setmore SignUp feature User should sign up with valid credentials" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (C:\Users\LENOVO\Desktop\Wdio_Scripts\test\specs\Setmore_signup.js)
                    at createTimeoutError (C:\Users\LENOVO\Desktop\Wdio_Scripts\node_modules\mocha\lib\errors.js:498:15)
                    at Test.Runnable._timeoutError (C:\Users\LENOVO\Desktop\Wdio_Scripts\node_modules\mocha\lib\runnable.js:431:10)
                    at Timeout.&lt;anonymous> (C:\Users\LENOVO\Desktop\Wdio_Scripts\node_modules\mocha\lib\runnable.js:246:24)
                    at listOnTimeout (node:internal/timers:559:17)
                    at processTimers (node:internal/timers:502:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>